# Generated by Django 3.0.5 on 2020-04-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_commets'),
    ]

    operations = [
        migrations.AddField(
            model_name='commets',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='commets',
            name='moder',
            field=models.BooleanField(default=False),
        ),
    ]
